spring.application.name=demo

spring.r2dbc.url=r2dbc:postgresql://bgahqehskcahpd1knmmf-postgresql.services.clever-cloud.com:50013/bgahqehskcahpd1knmmf
spring.r2dbc.username=ua0soeub7hwmgclmunyb
spring.r2dbc.password=eFe5vMqoeTfQiedtKol9ygFTMTcgSY
spring.r2dbc.pool.enabled=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= none
spring.datasource.driverClassName= org.postgresql.Driver
logging.level.org.springframework.r2dbc=DEBUG
